apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus-deployment
  labels:
    app: prometheus
    purpose: example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prometheus
      purpose: example
  serviceName: "prometheus-example-service"      
  template:
    metadata:
      name: prometheus
      labels:
        app: prometheus
        purpose: example
    spec:            
      containers:
      - name: prometheus-example
        image: prom/prometheus        
        volumeMounts:
          - name: config-volume
            mountPath: /etc/prometheus/prometheus.yml
            subPath: prometheus.yml
          - name: rules-general
            mountPath: /etc/prometheus/rules/generalrules.yaml
            subPath: generalrules.yaml
          - name: prometheus-metrics-db
            mountPath: /data
        args:
        - --storage.tsdb.path=/data
        - --storage.tsdb.retention=400d           
        - --config.file=/etc/prometheus/prometheus.yml
        ports:
        - containerPort: 9090
      volumes:
        - name: config-volume
          configMap:
           name: prometheus-example-cm
        - name: rules-general
          configMap:
           name: prometheus-rules-general     
  volumeClaimTemplates:
    - metadata:
        name: prometheus-metrics-db
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi           
---
kind: Service
apiVersion: v1
metadata:
  name: prometheus-example-service
spec:
  selector:
    app: prometheus
    purpose: example
  ports:
  - name: promui
    protocol: TCP
    port: 9090
    targetPort: 9090
