apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-discover
  labels:
    serviceapp: redis
spec:
  endpoints:
  - interval: 30s
    port: prom
  selector:
    matchLabels:
      app: redis